const TermConstants = {
  TERMS_RECEIVED: "TERMS_RECEIVED",
  TERM_RECEIVED: "TERM_RECEIVED",
  AUTHOR_TERMS_RECEIVED: "AUTHOR_TERMS_RECEIVED",
  UPDATE_TERM: "UPDATE_TERM"
};

module.exports = TermConstants;
