# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9c49e559688095b9d1d624478f7d12355b7e45879e6b1b8a4c6c42f112e130257a1bbf5590ae94d233be372528956c482378a00515c6031d56af7628bb859cff

test:
  secret_key_base: ae55c6c8ca9a7b4d9f57b51db59bd6a691a8c29bcdcad87f44494e0899d6ecd21c9b84a9e7d14674d2515488cde5f84b7603b3e70abbfdb3d884d308b535d6df

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
